import numpy as np
import xml.etree.ElementTree as ET



def create_mesh_from_points(x, y, z):
    # Flatten the arrays
    x = x.flatten()
    y = y.flatten()
    z = z.flatten()

    # Stack coordinates into vertices
    vertices = np.vstack((x, y, z)).T

    # Create faces (triangles)
    u_steps = len(np.unique(x))
    v_steps = len(np.unique(y))
    faces = []

    for i in range(v_steps - 1):
        for j in range(u_steps - 1):
            idx = i * u_steps + j
            idx_next = idx + u_steps

            # Each quadrilateral on the sphere is divided into two triangles
            faces.append([idx, idx + 1, idx_next + 1])
            faces.append([idx, idx_next + 1, idx_next])

    return vertices, faces




def write_object_xml(vertices, faces, unit="millimeter"):
    # Create root element
    model = ET.Element('model', attrib={
        'unit': unit,
        'xml:lang': 'en-US',
        'xmlns': 'http://schemas.microsoft.com/3dmanufacturing/core/2015/02'
    })

    # Add metadata
    metadata = ET.SubElement(model, 'metadata', attrib={'name': 'Copyright'})
    metadata.text = 'Generated by Python script.'

    # Resources
    resources = ET.SubElement(model, 'resources')
    obj = ET.SubElement(resources, 'object', attrib={'id': '1', 'type': 'model'})
    mesh = ET.SubElement(obj, 'mesh')

    # Vertices
    vertices_elem = ET.SubElement(mesh, 'vertices')
    for v in vertices:
        ET.SubElement(vertices_elem, 'vertex', attrib={
            'x': str(v[0]),
            'y': str(v[1]),
            'z': str(v[2])
        })

    # Triangles
    triangles_elem = ET.SubElement(mesh, 'triangles')
    for f in faces:
        ET.SubElement(triangles_elem, 'triangle', attrib={
            'v1': str(f[0]),
            'v2': str(f[1]),
            'v3': str(f[2])
        })

    # Build
    build = ET.SubElement(model, 'build')
    ET.SubElement(build, 'item', attrib={'objectid': '1'})

    # Convert to string
    xml_str = ET.tostring(model, encoding='utf-8', method='xml')
    return xml_str.decode('utf-8')


if __name__ == "__main__":

    from shapes.sphere import generate_sphere
    # Generate geometry
    x, y, z = generate_sphere(radius=1, u_steps=20, v_steps=20)

    # Create mesh
    vertices, faces = create_mesh_from_points(x, y, z)

    # Write XML
    object_xml = write_object_xml(vertices, faces)

    # Save to file or print
    with open('sphere.xml', 'w') as f:
        f.write(object_xml)

    print("object.xml file has been generated.")
